### ISSUE TITLE
Is there a way to prevent this error?

### ISSUE THREAD

**Issue by anseltaft** [umami-software/umami#2178]
### Describe the Bug

Twice in two weeks  the following error appeared when I tried to pull up Umami's dashboard:

```
Something went wrong

[@formatjs/intl] An `id` must be provided to format a message. You can either: 1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin) or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR 2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id) to autofix this issue
Error: [@formatjs/intl] An `id` must be provided to format a message. You can either:
1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
to autofix this issue
    at ep (https://subdomain.mydomain.com/_next/static/chunks/pages/_app-d25b7d6c3a248600.js:1:160)
    at eE (https://subdomain.mydomain.com/_next/static/chunks/pages/_app-d25b7d6c3a248600.js:6:577936)
    at e4 (https://subdomain.mydomain.com/_next/static/chunks/pages/_app-d25b7d6c3a248600.js:6:587683)
    at F (https://subdomain.mydomain.com/_next/static/chunks/pages/dashboard-ef3c6f276df533cc.js:1:5257)
    at ab (https://subdomain.mydomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:60915)
    at ud (https://subdomain.mydomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:72801)
    at i (https://subdomain.mydomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:120370)
    at oO (https://subdomain.mydomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:99112)
    at https://subdomain.mydomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:98979
    at oF (https://subdomain.mydomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:98986)
```

From a previous issue I understood this to mean there was an Umami update and I needed to update my docker instance.

The question I'm hoping to find an answer to is is there a way to prevent the toolchain error when a new version is ready? How can I make things less dependent on updates so I can update when I'm ready to and not vice-versa?

Any feedback would be appreciated.

Cheers

### Database

PostgreSQL

### Relevant log output

```shell
Something went wrong

[@formatjs/intl] An `id` must be provided to format a message. You can either: 1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin) or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR 2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id) to autofix this issue
Error: [@formatjs/intl] An `id` must be provided to format a message. You can either:
1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
to autofix this issue
    at ep (https://subdomain.mydomain.com/_next/static/chunks/pages/_app-d25b7d6c3a248600.js:1:160)
    at eE (https://subdomain.mydomain.com/_next/static/chunks/pages/_app-d25b7d6c3a248600.js:6:577936)
    at e4 (https://subdomain.mydomain.com/_next/static/chunks/pages/_app-d25b7d6c3a248600.js:6:587683)
    at F (https://subdomain.mydomain.com/_next/static/chunks/pages/dashboard-ef3c6f276df533cc.js:1:5257)
    at ab (https://subdomain.mydomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:60915)
    at ud (https://subdomain.mydomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:72801)
    at i (https://subdomain.mydomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:120370)
    at oO (https://subdomain.mydomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:99112)
    at https://subdomain.mydomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:98979
    at oF (https://subdomain.mydomain.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:98986)
```

### Which browser are you using? (if relevant)

Latest Chrome

### How are you deploying your application? (if relevant)

Docker Compose

**Comment by niklas-stegmann** [comment]
I also have this problem for the second time, since 2 weeks.

**Comment by M1nTT** [comment]
Same error, did you install with Docker-conpose? The mirror image on Dokcer Hub is a year old, so you get this error. This bug is fixed in the latest version, but you can't update to the latest version via Docker-compose.

https://hub.docker.com/r/umamisoftware/umami/tags

**Comment by niklas-stegmann** [comment]
> Same error, did you install with Docker-compose? The image on Dokcer Hub is a year old, so you get this error. This bug is fixed in the latest version, but you can't update to the latest version via Docker-compose.
> 
> https://hub.docker.com/r/umamisoftware/umami/tags

I'm not using the docker hub image. I use the official image from "docker.umami.dev/umami-software/umami:postgresql-latest" as described in the documentation: https://umami.is/docs/install

**Comment by mikecao** [comment]
@anseltaft you can set `DISABLE_UPDATES`, see https://umami.is/docs/environment-variables

However, the version with this error also had an bug with checking updates. I'd suggest updating to the latest, then setting that environment variable.

**Comment by franciscao633** [comment]
Is your image updated to v2.4.0? We introduced this error it one the recent releases, but starting in v2.4.0, you should not be forced to update to the latest and still have a functioning umami. You can manually pull the latest `docker pull docker.umami.dev/umami-software/umami:postgresql-latest`. If this comes back next release, please let us know.

**Comment by anseltaft** [comment]
I updated each time the dashboard displayed the error on the dashboard. If it's fixed in the latest I'll trust the process.

I can confirm the same/correct origin is in my docker compose file: docker.umami.dev/umami-software/umami:postgresql-latest

Thank you all for chiming in!
