### ISSUE TITLE
Incorrect referrer parameter in /api/send 

### ISSUE THREAD

**Issue by broscr** [umami-software/umami#2765]
### Describe the Bug

When redirecting from Google to a website, it was detected that the document. referrer was correct, but the referrer carried in the request sent by/API/send was incorrect, resulting in the source domain name being none in the monitoring data

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.11.3

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

NodeJS v: 18.19.1 - NextJS v:12.0.7

**Comment by jungju** [comment]
I am experiencing the same issue. I am also using Next.js.

**Comment by FabioGodoyy** [comment]
I'm facing a similar problem where the document.referrer is accurate, but the referrer passed in the /api/send request is incorrect, leading to the absence of the originating domain in the analytics data. My setup includes NodeJS v18.17.1 and NextJS v14.1.0. Has anyone found a workaround for this issue?

**Comment by fxck** [comment]
Having the same problem, funnily enough, when I used a manually beautified version of the script.js it works properly.

**Comment by fxck** [comment]
Alright, using the script from source ends up in not sending the referrer either. The only way I got it working was using a beautified of an older script. I'll try to debug it.

**Comment by fxck** [comment]
<img width="1008" alt="image" src="https://github.com/user-attachments/assets/f25c455c-e342-4deb-922e-370b364b18f9">

so, something seems to be happening with `currentRef` inside the `init()` function, before calling init it still has the correct value, inside init it does not

**Comment by fxck** [comment]
`handlePush` is the cuplrit, it changes the referrer before it has a change to send the initial request

<img width="406" alt="image" src="https://github.com/user-attachments/assets/d93bf868-f474-4d21-bd04-9e384f334a94">

<img width="501" alt="image" src="https://github.com/user-attachments/assets/f318d659-aeed-47c9-9559-2a4866002112">

**Comment by fxck** [comment]
This should work as a temp fix https://gist.github.com/fxck/4f31c37eb9a6fbca09c39518c07e55e6 use at your own risk.

**Comment by obstkompost** [comment]
i think i have the same issue

**Comment by mikecao** [comment]
@fxck Can you open a PR with your changes?

**Comment by obstkompost** [comment]
it would be great, if this could be fixed in the next version

**Comment by fxck** [comment]
@mikecao I could, but I didn't because I had to do some significant changes and hack around the way the script is initialized, including adding a little event queue.  And I'm absolutely not sure that it won't break any other use cases. I would be the best if the person that wrote the script originally looked into my [findings here](https://github.com/umami-software/umami/issues/2765#issuecomment-2286107395) and fixed it properly.

**Comment by mikecao** [comment]
This is now fixed in dev, https://github.com/umami-software/umami/commit/291c64f7b0b5c46667f4e80e0580c6b00b65a607

Will get a release out soon.

**Comment by mikecao** [comment]
Fixed in v2.13.2.

**Comment by andreagrandi** [comment]
![Screenshot 2024-08-30 at 19 13 34](https://github.com/user-attachments/assets/65d98d03-9b26-44a9-ad4f-9b44f911a2b8)

I'm running the 2.13.2 version but as you can see from the screenshot I'm still experiencing this bug.
Note: I've **updated the app yesterday** and **the data you see is only from today**, so the bug is still present.
